yarnPath: .yarn/releases/yarn-3.3.1.cjs
nodeLinker: pnp
packageExtensions:
  "styled-components@*":
    dependencies:
      "react-is": "^18.2.0"
  "webpack-dev-middleware@*":
    dependencies:
      "webpack": "^5.75.0"
